### ISSUE TITLE
Adicionar enum para possiveis `feelings` de uma entrada.

### ISSUE THREAD

**Issue by marclerodrigues** [teresinahc/carambolo#3]
![photo5170656620680685644](https://user-images.githubusercontent.com/8514920/67147203-22274e80-f269-11e9-94b2-e6d9a2342db4.jpg)

**Comment by raicg** [comment]
https://github.com/marclerodrigues/carambolo/pull/20
On this PR I changed feelings in Entries to be a integer instead of a string and then I created a enum for it.
I started the enum with 4 feelings, but anyone can add more in entry.rb model.

On this PR I configured the i18n to use PT-BR and started a dictionary on: config/locales/pt-BR.yml
there you can find the translation about the feelings and other words that the project may use.
